### ISSUE TITLE
Documentation: add images of the completed PCB installed in the case

### ISSUE THREAD

**Issue by SniderThanYou** [Lupinixx/SlimeVR-Hyperion-BMI160-PCB#4]
Hey! Thanks so much for sharing this project. It looks like the recommended SS12D00G3 switches sit flush to the board, but the case looks like the switch should be mounted sideways. Would you add a picture or two showing how you made it work? Thanks!

**Comment by Jetss3** [comment]
I would also really like to see how that was done, cheers!

**Comment by Lupinixx** [comment]
Added some images in the Photos folder
