### ISSUE TITLE
D1 Mini has its USB-C port mounted on the top, leading to too large of an offset

### ISSUE THREAD

**Issue by InconsolableCellist** [Lupinixx/SlimeVR-Hyperion-BMI160-PCB#7]
I'm using the D1 mini for assembly, and putting it on the normal pin headers and placing it on top of the PCB, the USB-C port doesn't line up with the cut-out in the case. This also means the lid won't close properly. I noticed in the photos that the ESP32 you're using has a micro USB port mounted on the bottom of its modular board, which lines up.

Would it be possible to make a D1 variant? It'd also be nice if the TP4056 could be mounted on normal pin headers too, with that ~1mm vertical offset, as it makes it easier and faster to solder.

![image](https://github.com/Lupinixx/SlimeVR-Hyperion-BMI160-PCB/assets/23345188/7653a400-ba20-4706-bb7e-578e86ca8556)

**Comment by ManicQuinn** [comment]
They are both D1 Mini's, the difference is that your's is V4.0, they're quite different, case wasn't designed for it

**Comment by InconsolableCellist** [comment]
I should've come back and updated this. The issue I was having was because I kept the spacers on the pin headers, elevating it and making it not quite fit. I deviated from the instructions which said the D1 Mini should lay flat on the PCB. I think the version I have will still fit fine, though I went on and made a new PCB just to fit in the BNO085.
